baseURL = "https://blog.nixlab.online/"
languageCode = "en-au"
title = "NixLab Blog"
theme = "hugo-theme-terminal"
[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  showFooter = true
  footerContent = "&copy; 2026 Nik Palmer &middot; <a href=\"https://nixlab.online\">NixLab</a>"

[params.twitter]
  creator = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "NixLab Blog"
    subtitle = "Notes on simulation, learning design & building things"
    owner = "Nik Palmer"
    keywords = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nixlab"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"

    [[languages.en.menu.main]]
      identifier = "portfolio"
      name = "Portfolio"
      url = "https://nixlab.online"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
